input_folder: "./my/dsds"    # Replace with your actual input folder path
output_folder: "output_docs"  # Replace with your desired output folder path
log_folder: "logs"           # Folder to store log files